### ISSUE TITLE
SyntaxError: 'await' outside function

### ISSUE THREAD

**Issue by sciaba** [iris-hep/analysis-grand-challenge#93]
If coffea.ipynb os converted to a script using nbconvert, the resulting script will abort with the message in the title, due to the statement

all_histograms = await utils.produce_all_histograms(...)

**Comment by alexander-held** [comment]
Hi @sciaba, this happens due to `asyncio` behaving differently in a notebook and a script. The version of the code to use in case of a script can be found a few lines below:

```python
    # as a script:
    # async def produce_all_the_histograms():
    #     return await utils.produce_all_histograms(fileset, get_query, TtbarAnalysis(DISABLE_PROCESSING, IO_FILE_PERCENT),
    #                                               use_dask=USE_DASK, ignore_cache=SERVICEX_IGNORE_CACHE, schema=AGCSchema)
    #
    # all_histograms = asyncio.run(produce_all_the_histograms())
```

Please comment out that part and remove the comment that fails, that should fix the issue.

We are planning to refactor the implementation to remove `asyncio` here and that will solve the issue. I'll update here when this is done (planned for the next few weeks).

**Comment by sciaba** [comment]
Thank you, my bad, I hadn't bothered reading the comment. :(
